package com.readypackets.mobile.ui

import android.content.Intent
import android.net.Uri
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.runtime.saveable.rememberSaveable
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.unit.dp
import com.readypackets.mobile.core.*
import kotlinx.coroutines.launch

@Composable fun MessagesScreen(container: AppContainer) { var page by remember { mutableStateOf<MessagesPage?>(null) }; var error by remember { mutableStateOf<String?>(null) }; LaunchedEffect(Unit) { container.api().get<MessagesPage>("/customer/messages").onSuccess { page = it }.onFailure { error = it.message } }; LazyColumn(Modifier.fillMaxSize().padding(16.dp), verticalArrangement = Arrangement.spacedBy(10.dp)) { item { Text("Messages", style = MaterialTheme.typography.headlineMedium) }; error?.let { item { Text(it, color = Danger) } }; page?.let { messages -> item { if (messages.items.isEmpty()) Text("No secure messages yet.", style = MaterialTheme.typography.bodyLarge) }; items(messages.items, key = { it.mobileMessageRef }) { message -> ElevatedCard { Column(Modifier.padding(16.dp)) { Text(message.projectName ?: message.publicOrderId ?: "ReadyPackets", style = MaterialTheme.typography.titleMedium); Text(message.body, style = MaterialTheme.typography.bodyMedium); Text(message.createdAt ?: "", style = MaterialTheme.typography.labelSmall) } } } } } }

@Composable fun NotificationsScreen(container: AppContainer) { var page by remember { mutableStateOf<NotificationsPage?>(null) }; var error by remember { mutableStateOf<String?>(null) }; LaunchedEffect(Unit) { container.api().get<NotificationsPage>("/customer/notifications").onSuccess { page = it }.onFailure { error = it.message } }; LazyColumn(Modifier.fillMaxSize().padding(16.dp), verticalArrangement = Arrangement.spacedBy(10.dp)) { item { Text("Updates", style = MaterialTheme.typography.headlineMedium) }; error?.let { item { Text(it, color = Danger) } }; page?.let { updates -> item { if (updates.items.isEmpty()) Text("No new customer updates.") }; items(updates.items, key = { "${it.kind}-${it.createdAt}-${it.publicOrderId}" }) { item -> ElevatedCard { Column(Modifier.padding(16.dp)) { Text(item.title, style = MaterialTheme.typography.titleMedium); Text(item.body); Text(item.createdAt ?: "", style = MaterialTheme.typography.labelSmall) } } } } } }

@Composable fun CustomerServicesScreen(container: AppContainer) { var screen by rememberSaveable { mutableStateOf("menu") }; when (screen) { "tickets" -> TicketsScreen(container) { screen = "menu" }; "community" -> CommunityScreen(container) { screen = "menu" }; "workspaces" -> WorkspacesScreen(container) { screen = "menu" }; "referrals" -> ReferralsScreen(container) { screen = "menu" }; "knowledge" -> KnowledgeScreen(container) { screen = "menu" }; "faqs" -> FAQsScreen(container) { screen = "menu" }; "security" -> BrowserEntrypointsScreen(container) { screen = "menu" }; "profile" -> ProfileScreen(container); else -> LazyColumn(Modifier.fillMaxSize().padding(16.dp), verticalArrangement = Arrangement.spacedBy(10.dp)) { item { Text("Customer services", style = MaterialTheme.typography.headlineMedium) }; item { ServiceButton("Profile and devices", Icons.Default.Person) { screen = "profile" } }; item { ServiceButton("Support tickets", Icons.Default.SupportAgent) { screen = "tickets" } }; item { ServiceButton("Packet Collective", Icons.Default.Groups) { screen = "workspaces" } }; item { ServiceButton("Referrals", Icons.Default.Redeem) { screen = "referrals" } }; item { ServiceButton("Community", Icons.Default.Forum) { screen = "community" } }; item { ServiceButton("Knowledge base", Icons.Default.MenuBook) { screen = "knowledge" } }; item { ServiceButton("Frequently asked questions", Icons.Default.HelpOutline) { screen = "faqs" } }; item { ServiceButton("Account and security", Icons.Default.Security) { screen = "security" } } } } }
@Composable private fun ServiceButton(label: String, icon: androidx.compose.ui.graphics.vector.ImageVector, action: () -> Unit) { ElevatedCard(onClick = action) { Row(Modifier.fillMaxWidth().padding(18.dp), horizontalArrangement = Arrangement.spacedBy(14.dp)) { Icon(icon, null, tint = Teal); Text(label, style = MaterialTheme.typography.titleMedium) } } }
@Composable private fun BackTitle(title: String, back: () -> Unit) { Row(Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.spacedBy(8.dp)) { TextButton(onClick = back) { Icon(Icons.Default.ArrowBack, "Back") }; Text(title, style = MaterialTheme.typography.headlineMedium) } }

@Composable fun TicketsScreen(container: AppContainer, back: () -> Unit) { var page by remember { mutableStateOf<TicketsPage?>(null) }; var subject by remember { mutableStateOf("") }; var body by remember { mutableStateOf("") }; var error by remember { mutableStateOf<String?>(null) }; val scope = rememberCoroutineScope(); fun load() { scope.launch { container.api().get<TicketsPage>("/customer/tickets").onSuccess { page = it }.onFailure { error = it.message } } }; LaunchedEffect(Unit) { load() }; LazyColumn(Modifier.fillMaxSize().padding(16.dp), verticalArrangement = Arrangement.spacedBy(10.dp)) { item { BackTitle("Support", back) }; page?.let { tickets -> items(tickets.items, key = { it.ticketNumber }) { ticket -> ElevatedCard { Column(Modifier.padding(16.dp)) { Text(ticket.subject, style = MaterialTheme.typography.titleMedium); Text("${ticket.ticketNumber} · ${ticket.status}", style = MaterialTheme.typography.labelSmall) } } } }; item { HorizontalDivider(); Text("New support ticket", style = MaterialTheme.typography.titleLarge); OutlinedTextField(subject, { subject = it }, label = { Text("Subject") }, modifier = Modifier.fillMaxWidth()); OutlinedTextField(body, { body = it }, label = { Text("Message") }, modifier = Modifier.fillMaxWidth().heightIn(min = 120.dp)); Button(onClick = { scope.launch { container.api().post<EmptyReply, Map<String, String>>("/customer/tickets", mapOf("subject" to subject, "body" to body, "category" to "general", "priority" to "normal")).onSuccess { subject = ""; body = ""; load() }.onFailure { error = it.message } } }, enabled = subject.length >= 5 && body.length >= 20, colors = ButtonDefaults.buttonColors(containerColor = Teal)) { Text("Send secure ticket") } }; error?.let { item { Text(it, color = Danger) } } } }

@Composable fun WorkspacesScreen(container: AppContainer, back: () -> Unit) { var page by remember { mutableStateOf<WorkspacesPage?>(null) }; var name by remember { mutableStateOf("") }; var error by remember { mutableStateOf<String?>(null) }; val scope = rememberCoroutineScope(); fun load() { scope.launch { container.api().get<WorkspacesPage>("/customer/workspaces").onSuccess { page = it }.onFailure { error = it.message } } }; LaunchedEffect(Unit) { load() }; LazyColumn(Modifier.fillMaxSize().padding(16.dp), verticalArrangement = Arrangement.spacedBy(10.dp)) { item { BackTitle("Packet Collective", back) }; page?.let { groups -> items(groups.items, key = { it.mobileWorkspaceRef }) { workspace -> ElevatedCard { Column(Modifier.padding(16.dp)) { Text(workspace.name, style = MaterialTheme.typography.titleMedium); Text("${workspace.role} · ${workspace.slug}", style = MaterialTheme.typography.labelSmall) } } } }; item { HorizontalDivider(); OutlinedTextField(name, { name = it }, label = { Text("New workspace name") }, modifier = Modifier.fillMaxWidth()); Button(onClick = { scope.launch { container.api().post<WorkspaceCreated, Map<String, String>>("/customer/workspaces", mapOf("name" to name)).onSuccess { name = ""; load() }.onFailure { error = it.message } } }, enabled = name.trim().length >= 2, colors = ButtonDefaults.buttonColors(containerColor = Teal)) { Text("Create workspace") } }; error?.let { item { Text(it, color = Danger) } } } }

@Composable fun ReferralsScreen(container: AppContainer, back: () -> Unit) { var value by remember { mutableStateOf<ReferralSummary?>(null) }; var error by remember { mutableStateOf<String?>(null) }; val context = LocalContext.current; LaunchedEffect(Unit) { container.api().get<ReferralSummary>("/customer/referrals").onSuccess { value = it }.onFailure { error = it.message } }; Column(Modifier.fillMaxSize().padding(16.dp), verticalArrangement = Arrangement.spacedBy(14.dp)) { BackTitle("Referrals", back); value?.let { referral -> ElevatedCard { Column(Modifier.padding(18.dp)) { Text("Your referral code", style = MaterialTheme.typography.labelLarge); Text(referral.code, style = MaterialTheme.typography.headlineMedium); Button(onClick = { context.startActivity(Intent.createChooser(Intent(Intent.ACTION_SEND).setType("text/plain").putExtra(Intent.EXTRA_TEXT, "Use my ReadyPackets referral code: ${referral.code}"), "Share referral code")) }) { Text("Share code") } } }; Text("${referral.stats.total} total · ${referral.stats.pending} pending · ${referral.stats.paid} paid") }; error?.let { Text(it, color = Danger) } } }

@Composable fun CommunityScreen(container: AppContainer, back: () -> Unit) { var page by remember { mutableStateOf<ForumTopicsPage?>(null) }; var error by remember { mutableStateOf<String?>(null) }; LaunchedEffect(Unit) { container.api().get<ForumTopicsPage>("/customer/community/topics").onSuccess { page = it }.onFailure { error = it.message } }; LazyColumn(Modifier.fillMaxSize().padding(16.dp), verticalArrangement = Arrangement.spacedBy(10.dp)) { item { BackTitle("Community", back) }; page?.let { topics -> items(topics.items, key = { it.slug }) { topic -> ElevatedCard { Column(Modifier.padding(16.dp)) { Text(topic.title, style = MaterialTheme.typography.titleMedium); topic.excerpt?.let { Text(it, maxLines = 2) }; Text("${topic.replyCount} replies · ${topic.author}", style = MaterialTheme.typography.labelSmall) } } } }; error?.let { item { Text(it, color = Danger) } } } }

@Composable fun KnowledgeScreen(container: AppContainer, back: () -> Unit) { var page by remember { mutableStateOf<KnowledgePage?>(null) }; var error by remember { mutableStateOf<String?>(null) }; LaunchedEffect(Unit) { container.api().get<KnowledgePage>("/customer/knowledge").onSuccess { page = it }.onFailure { error = it.message } }; LazyColumn(Modifier.fillMaxSize().padding(16.dp), verticalArrangement = Arrangement.spacedBy(10.dp)) { item { BackTitle("Knowledge base", back) }; page?.let { articles -> items(articles.items, key = { it.slug }) { article -> ElevatedCard { Column(Modifier.padding(16.dp)) { Text(article.title, style = MaterialTheme.typography.titleMedium); article.excerpt?.let { Text(it, maxLines = 3) } } } } }; error?.let { item { Text(it, color = Danger) } } } }

@Composable fun FAQsScreen(container: AppContainer, back: () -> Unit) { var page by remember { mutableStateOf<FAQsPage?>(null) }; var error by remember { mutableStateOf<String?>(null) }; LaunchedEffect(Unit) { container.api().get<FAQsPage>("/public/faqs").onSuccess { page = it }.onFailure { error = it.message } }; LazyColumn(Modifier.fillMaxSize().padding(16.dp), verticalArrangement = Arrangement.spacedBy(10.dp)) { item { BackTitle("Frequently asked questions", back) }; page?.let { faqs -> items(faqs.items, key = { it.question }) { faq -> ElevatedCard { Column(Modifier.padding(16.dp)) { Text(faq.question, style = MaterialTheme.typography.titleMedium); Text(faq.answerMarkdown) } } } }; error?.let { item { Text(it, color = Danger) } } } }

@Composable fun BrowserEntrypointsScreen(container: AppContainer, back: () -> Unit) { var links by remember { mutableStateOf<BrowserEntrypoints?>(null) }; var error by remember { mutableStateOf<String?>(null) }; val context = LocalContext.current; fun open(url: String) { context.startActivity(Intent(Intent.ACTION_VIEW, Uri.parse(url))) }; LaunchedEffect(Unit) { container.api().get<BrowserEntrypoints>("/public/browser-entrypoints").onSuccess { links = it }.onFailure { error = it.message } }; Column(Modifier.fillMaxSize().padding(16.dp), verticalArrangement = Arrangement.spacedBy(12.dp)) { BackTitle("Account and security", back); links?.let { item -> Button({ open(item.registrationUrl) }, Modifier.fillMaxWidth()) { Text("Register customer account") }; Button({ open(item.emailVerificationUrl) }, Modifier.fillMaxWidth()) { Text("Verify email") }; Button({ open(item.passwordRecoveryUrl) }, Modifier.fillMaxWidth()) { Text("Reset password") }; Button({ open(item.customerSecurityUrl) }, Modifier.fillMaxWidth()) { Text("Password, MFA, and sessions") }; Button({ open(item.legalUrl) }, Modifier.fillMaxWidth()) { Text("Legal and privacy") }; Button({ open(item.contactUrl) }, Modifier.fillMaxWidth()) { Text("Contact ReadyPackets") }; Text("These sensitive actions open the verified ReadyPackets Portal in your system browser. Passwords, MFA values, and payment data are never entered in the app.", style = MaterialTheme.typography.bodySmall) }; error?.let { Text(it, color = Danger) } } }
