package com.readypackets.mobile.ui

import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import com.readypackets.mobile.core.*
import kotlinx.coroutines.launch

@Composable fun OrdersScreen(container: AppContainer) { var orders by remember { mutableStateOf<List<OrderSummary>>(emptyList()) }; var error by remember { mutableStateOf<String?>(null) }; var selected by remember { mutableStateOf<OrderSummary?>(null) }; var composing by remember { mutableStateOf(false) }; var refreshKey by remember { mutableIntStateOf(0) }; val scope = rememberCoroutineScope(); LaunchedEffect(refreshKey) { container.api().get<OrdersPage>("/orders?limit=20").onSuccess { orders = it.items }.onFailure { error = it.message } }; when { composing -> OrderComposerScreen(container, onClose = { composing = false }, onCreated = { refreshKey++ }); selected != null -> OrderDetailScreen(container, selected!!, { selected = null }); else -> LazyColumn(Modifier.fillMaxSize().padding(16.dp), verticalArrangement = Arrangement.spacedBy(10.dp)) { item { Row(Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.SpaceBetween) { Text("Orders", style = MaterialTheme.typography.headlineMedium); Button(onClick = { composing = true }, colors = ButtonDefaults.buttonColors(containerColor = Teal)) { Text("Place order") } } }; item { Text("Create a request from currently listed packets. The Portal confirms pricing, payment, and activation.", style = MaterialTheme.typography.bodyMedium) }; error?.let { item { Text(it, color = Danger) } }; items(orders, key = { it.publicOrderId }) { order -> ElevatedCard(onClick = { selected = order }) { Column(Modifier.padding(16.dp)) { Text(order.projectName ?: order.publicOrderId, style = MaterialTheme.typography.titleMedium); Text(order.currentStage ?: order.status, style = MaterialTheme.typography.bodyMedium); Spacer(Modifier.height(8.dp)); LinearProgressIndicator(progress = { order.completionPercent / 100f }, modifier = Modifier.fillMaxWidth(), color = Teal); Text("${order.completionPercent}%", style = MaterialTheme.typography.labelMedium); if (order.attention != "none") Text("Action needed", color = Danger, style = MaterialTheme.typography.labelLarge) } } } } } }
@Composable private fun OrderDetailScreen(container: AppContainer, summary: OrderSummary, back: () -> Unit) { var detail by remember { mutableStateOf<OrderDetail?>(null) }; var error by remember { mutableStateOf<String?>(null) }; val scope = rememberCoroutineScope(); LaunchedEffect(summary.publicOrderId) { scope.launch { container.api().get<OrderDetail>("/orders/${summary.publicOrderId}").onSuccess { detail = it }.onFailure { error = it.message } } }; Column(Modifier.fillMaxSize().padding(16.dp), verticalArrangement = Arrangement.spacedBy(16.dp)) { TextButton(onClick = back) { Text("Back to orders") }; Text(detail?.projectName ?: summary.projectName ?: summary.publicOrderId, style = MaterialTheme.typography.headlineSmall); ElevatedCard { Column(Modifier.padding(16.dp)) { Text(detail?.currentStage ?: summary.currentStage ?: summary.status, style = MaterialTheme.typography.titleMedium); LinearProgressIndicator(progress = { (detail?.completionPercent ?: summary.completionPercent) / 100f }, modifier = Modifier.fillMaxWidth(), color = Teal); Text("Payment status: ${detail?.paymentStatus ?: summary.paymentStatus}", style = MaterialTheme.typography.bodyMedium) } }; Text("Files and audio", style = MaterialTheme.typography.titleMedium); Text("Choose files or record audio only for a server-authorized workflow step. The app never decides whether a phase is complete or locked."); Text("My Business Packets", style = MaterialTheme.typography.titleMedium); Text("Approved final deliverables appear only after server authorization."); error?.let { Text(it, color = Danger) } } }
