package com.readypackets.mobile.ui

import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import com.readypackets.mobile.core.*
import kotlinx.coroutines.launch

@Composable fun ProfileScreen(container: AppContainer) { var profile by remember { mutableStateOf<Profile?>(null) }; var devices by remember { mutableStateOf<List<DeviceRecord>>(emptyList()) }; var deletion by remember { mutableStateOf(false) }; val scope = rememberCoroutineScope(); LaunchedEffect(Unit) { scope.launch { container.api().get<Profile>("/me").onSuccess { profile = it }; container.api().get<DevicesPage>("/me/devices").onSuccess { devices = it.items } } }; if (deletion) { DeletionScreen(container) { deletion = false }; return }; LazyColumn(Modifier.fillMaxSize().padding(16.dp), verticalArrangement = Arrangement.spacedBy(12.dp)) { item { Text("Profile", style = MaterialTheme.typography.headlineMedium) }; profile?.let { p -> item { ElevatedCard { Column(Modifier.padding(16.dp)) { Text(p.displayName, style = MaterialTheme.typography.titleLarge); Text(p.email); Text("${p.role.replaceFirstChar { it.uppercase() }} account"); Text(if (p.mfaEnabled) "Two-factor authentication enabled" else "Two-factor authentication needs attention", color = if (p.mfaEnabled) Teal else Danger) } } } }; item { Text("Your devices", style = MaterialTheme.typography.titleLarge) }; items(devices) { d -> ElevatedCard { Column(Modifier.padding(16.dp)) { Text(d.deviceName ?: "${d.platform.replaceFirstChar { it.uppercase() }} device"); Text("${d.platform} • v${d.appVersion} • ${d.status}"); if (d.current) Text("This device", color = Teal) } } }; item { OutlinedButton(onClick = { deletion = true }, modifier = Modifier.fillMaxWidth()) { Text("Request account deletion") } }; item { Button(onClick = { container.logout() }, colors = ButtonDefaults.buttonColors(containerColor = Danger), modifier = Modifier.fillMaxWidth()) { Text("Sign out") } } } }
@Composable private fun DeletionScreen(container: AppContainer, back: () -> Unit) { var phrase by remember { mutableStateOf("") }; var message by remember { mutableStateOf<String?>(null) }; val scope = rememberCoroutineScope(); Column(Modifier.fillMaxSize().padding(16.dp), verticalArrangement = Arrangement.spacedBy(16.dp)) { TextButton(onClick = back) { Text("Back") }; Text("Request account deletion", style = MaterialTheme.typography.headlineSmall); Text("This will immediately deactivate your account. Completed engagement records may be retained where the Privacy Policy requires it."); OutlinedTextField(value = phrase, onValueChange = { phrase = it }, label = { Text("Type DELETE MY ACCOUNT") }, modifier = Modifier.fillMaxWidth()); Button(onClick = { scope.launch { container.api().post<DeletionReply, DeletionRequest>("/me/data-deletion-request", DeletionRequest(phrase)).onSuccess { message = it.message }.onFailure { message = it.message } } }, enabled = phrase == "DELETE MY ACCOUNT", colors = ButtonDefaults.buttonColors(containerColor = Danger), modifier = Modifier.fillMaxWidth()) { Text("Request deletion") }; message?.let { Text(it) } } }
