package com.readypackets.mobile.core

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable data class TokenSet(@SerialName("access_token") val accessToken: String, @SerialName("token_type") val tokenType: String, @SerialName("expires_in") val expiresIn: Int, @SerialName("refresh_token") val refreshToken: String)
@Serializable data class ApiProblem(val title: String, val code: String, val detail: String? = null)
@Serializable data class Profile(val id: String, val displayName: String, val email: String, val role: String, val capabilities: List<String>, val mfaEnabled: Boolean, val emailVerified: Boolean)
@Serializable data class Dashboard(val orderCount: Int, val attentionCount: Int, val currentOrders: List<DashboardOrder>)
@Serializable data class DashboardOrder(val publicOrderId: String, val projectName: String? = null, val status: String, val completionPercent: Int, val currentStage: String? = null, val attention: String)
@Serializable data class OrderSummary(val publicOrderId: String, val projectName: String? = null, val status: String, val paymentStatus: String, val completionPercent: Int, val currentStage: String? = null, val attention: String, val dueAt: String? = null, val deliveredAt: String? = null, val createdAt: String? = null)
@Serializable data class OrdersPage(val items: List<OrderSummary>, val nextCursor: String? = null)
@Serializable data class OrderDetail(val publicOrderId: String, val projectName: String? = null, val status: String, val paymentStatus: String, val completionPercent: Int, val currentStage: String? = null)
@Serializable data class DeviceRecord(val id: String, val platform: String, val appVersion: String, val deviceName: String? = null, val status: String, val lastSeenAt: String? = null, val current: Boolean)
@Serializable data class DevicesPage(val items: List<DeviceRecord>)
@Serializable data class DeletionRequest(val confirmPhrase: String)
@Serializable data class DeletionReply(val accepted: Boolean, val openOrders: Int, val message: String)
@Serializable data class CatalogPacket(val sku: String, val name: String, val tier: String, val priceCents: Int? = null, val customPricing: Boolean, val deliveryEstimate: String, val outcome: String? = null, val description: String? = null)
@Serializable data class CatalogGroup(val slug: String, val number: Int, val name: String, val category: String, val summary: String? = null, val packets: List<CatalogPacket>)
@Serializable data class CatalogPage(val items: List<CatalogGroup>)
@Serializable data class OrderSelection(val sku: String, val quantity: Int = 1)
@Serializable data class CreateOrderRequest(val selections: List<OrderSelection>, val projectName: String? = null)
@Serializable data class CreatedMobileOrder(val publicOrderId: String, val projectName: String? = null, val status: String, val paymentStatus: String, val totalCents: Int, val requiresCustomQuote: Boolean)
@Serializable data class CreateOrderReply(val order: CreatedMobileOrder, val nextAction: String, val message: String)
@Serializable data class CustomerFile(val mobileFileRef: String, val originalName: String, val extension: String? = null, val sizeBytes: Int, val durationSeconds: Double? = null, val category: String? = null, val phase: String? = null, val version: Int, val createdAt: String? = null, val uploadedByStaff: Boolean? = null, val audio: Boolean)
@Serializable data class CustomerFilesPage(val items: List<CustomerFile>)
@Serializable data class WorkflowStage(val key: String, val label: String? = null, val description: String? = null, val advanceMode: String? = null, val capabilities: List<String>? = null)
@Serializable data class CustomerWorkflow(val name: String? = null, val description: String? = null, val customerPresentation: String? = null, val stages: List<WorkflowStage>? = null)
@Serializable data class CustomerOrderCore(val publicOrderId: String, val projectName: String? = null, val status: String, val statusLabel: String? = null, val paymentStatus: String, val totalCents: Int, val completionPercent: Int, val dueAt: String? = null, val deliveredAt: String? = null, val createdAt: String? = null)
@Serializable data class WorkflowProgress(val currentPhaseLabel: String? = null, val completionPercent: Int? = null)
@Serializable data class CustomerOrderDetail(val order: CustomerOrderCore, val workflow: CustomerWorkflow? = null, val deliverables: List<CustomerFile> = emptyList(), val messages: List<CustomerMessage> = emptyList(), val workflowProgress: WorkflowProgress? = null)
@Serializable data class CustomerMessage(val mobileMessageRef: String, val publicOrderId: String? = null, val projectName: String? = null, val authorRole: String? = null, val body: String, val createdAt: String? = null, val unread: Boolean? = null)
@Serializable data class MessagesPage(val unreadCount: Int, val items: List<CustomerMessage>)
@Serializable data class NotificationItem(val kind: String, val publicOrderId: String? = null, val createdAt: String? = null, val title: String, val body: String)
@Serializable data class NotificationsPage(val items: List<NotificationItem>, val unreadCount: Int, val generatedAt: String)
@Serializable data class Invoice(val invoiceNumber: String, val orderNumber: String, val issuedAt: String, val paidAt: String? = null, val subtotalCents: Int, val discountCents: Int, val totalCents: Int, val actualCustomerPaidCents: Int, val paymentEvidenceLabel: String, val customerVisible: Boolean)
@Serializable data class CheckoutHandoff(val checkoutUrl: String, val provider: String, val message: String)
@Serializable data class SupportTicket(val ticketNumber: String, val subject: String, val category: String, val status: String, val priority: String, val lastReplyAt: String? = null, val createdAt: String? = null)
@Serializable data class TicketsPage(val items: List<SupportTicket>)
@Serializable data class ForumCategory(val slug: String, val name: String, val description: String? = null)
@Serializable data class ForumCategoriesPage(val items: List<ForumCategory>)
@Serializable data class ForumTopic(val slug: String, val title: String, val excerpt: String? = null, val pinned: Boolean, val locked: Boolean, val replyCount: Int, val author: String, val lastPostAt: String? = null, val createdAt: String? = null)
@Serializable data class ForumTopicsPage(val items: List<ForumTopic>)
@Serializable data class Workspace(val mobileWorkspaceRef: String, val name: String, val slug: String, val role: String, val youOwnThisWorkspace: Boolean)
@Serializable data class WorkspacesPage(val items: List<Workspace>)
@Serializable data class WorkspaceCreated(val mobileWorkspaceRef: String, val slug: String)
@Serializable data class ReferralStats(val total: Int, val pending: Int, val approved: Int, val paid: Int, val totalRewardCents: Int, val paidRewardCents: Int)
@Serializable data class ReferralSummary(val code: String, val stats: ReferralStats)
@Serializable data class KnowledgeArticle(val slug: String, val title: String, val excerpt: String? = null, val category: String? = null, val updatedAt: String? = null)
@Serializable data class KnowledgePage(val items: List<KnowledgeArticle>)
@Serializable data class FAQ(val question: String, val answerMarkdown: String, val category: String? = null, val updatedAt: String? = null)
@Serializable data class FAQsPage(val items: List<FAQ>)
@Serializable data class BrowserEntrypoints(val registrationUrl: String, val emailVerificationUrl: String, val passwordRecoveryUrl: String, val customerSecurityUrl: String, val legalUrl: String, val contactUrl: String)
@Serializable data class EmptyReply(val ok: Boolean? = null)
@Serializable data class DeviceRegistration(val deviceId: String, val platform: String, val appVersion: String, val deviceName: String? = null, val pushPlatform: String? = null, val pushToken: String? = null)
@Serializable data class DeviceRegistrationReply(val registered: Boolean)
